# Generated by Django 5.1.2 on 2024-10-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_alert', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
    ]
