# Generated by Django 5.1.2 on 2024-10-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_alert', '0003_alter_friendship_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyalert',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
