# Generated by Django 5.1.2 on 2024-10-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_alert', '0004_safetyalert_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyalert',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='safetyalert',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
