# Generated by Django 5.1.2 on 2024-10-23 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safety_alert', '0008_friendship_created_at_profile_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safetyalert',
            name='location',
        ),
        migrations.RemoveField(
            model_name='safetyalert',
            name='user_location',
        ),
    ]
